In [12]:
import pandas as pd
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), '..'))

from constants import Constants
constants = Constants()
datapath = constants.DATAPATH

In [ ]:
inp914086 = pd.read_excel("../" + datapath + "/management/914086.xlsx")
inp914087 = pd.read_excel("../" + datapath + "/eurobank/914087.xlsx")
inp914351 = pd.read_excel("../" + datapath + "914351.xlsx")
inp914354 = pd.read_excel("../" + datapath + "914354.xlsx")
inp914631 = pd.read_excel("../" + datapath + "914631.xlsx")
inp914632 = pd.read_excel("../" + datapath + "914632.xlsx")
inp_oct   = pd.read_excel("../" + datapath + "ΠΟΛΛΑΠΛΟΣ 02.10.2025.xlsx")

dfs = {
    "914086": inp914086,
    "914087": inp914087,
    "914351": inp914351,
    "914354": inp914354,
    "914631": inp914631,
    "914632": inp914632
}

comparative_oct = pd.read_excel("../" + datapath + "ΣΥΓΚΡΙΤΙΚΟΣ ΕΥΔΑΠ 02.10.2025.xlsx")

In [5]:
# inp914632.columns.tolist()

# ΕΛΕΓΧΟΙ ΓΙΑ ΚΑΘΕ ΑΡΧΕΙΟ

## ΙΔΙΟΣ ΑΡΙΘΜΟΣ ΣΤΗΛΩΝ

In [57]:
for key, df in dfs.items():
    print(f"DataFrame {key} has {df.shape[1]} columns.")

DataFrame 914086 has 42 columns.
DataFrame 914087 has 43 columns.
DataFrame 914351 has 43 columns.
DataFrame 914354 has 43 columns.
DataFrame 914631 has 43 columns.
DataFrame 914632 has 43 columns.

## ΙΔΙΑ ΟΝΟΜΑΤΑ ΣΤΗΛΩΝ

In [58]:
keys_list = list(dfs.keys())
for i in range(len(keys_list)):
    for j in range(i + 1, len(keys_list)):
        
        key = keys_list[i]
        other_key = keys_list[j]
        df = dfs[key]
        other_df = dfs[other_key]
        
        if df.shape[1] == other_df.shape[1]:
            print(f"DataFrames {key} and {other_key} have the same number of columns: {df.shape[1]}")
            common_columns = set(df.columns).intersection(set(other_df.columns))
            if len(common_columns) == df.shape[1] and len(common_columns) == other_df.shape[1]:
                print(f"DataFrames {key} and {other_key} have exactly the same columns")
        else:
            print(f"DataFrames {key} and {other_key} have different number of columns: {df.shape[1]} vs {other_df.shape[1]}")
            common_columns = set(df.columns).intersection(set(other_df.columns))
            if common_columns:
                non_common_cols = set(df.columns).symmetric_difference(other_df.columns)
                print(f"DataFrames {key} and {other_key} have {len(non_common_cols)} non-common columns: {non_common_cols}")
            else:
                print(f"DataFrames {key} and {other_key} have no columns in common")
            print("=======")
            continue
        
        print("=======")

DataFrames 914086 and 914087 have different number of columns: 42 vs 43
DataFrames 914086 and 914087 have 1 non-common columns: {'ΔΙΑΔΡΟΜΗ'}
=======
DataFrames 914086 and 914351 have different number of columns: 42 vs 43
DataFrames 914086 and 914351 have 1 non-common columns: {'ΔΙΑΔΡΟΜΗ'}
=======
DataFrames 914086 and 914354 have different number of columns: 42 vs 43
DataFrames 914086 and 914354 have 1 non-common columns: {'ΔΙΑΔΡΟΜΗ'}
=======
DataFrames 914086 and 914631 have different number of columns: 42 vs 43
DataFrames 914086 and 914631 have 1 non-common columns: {'ΔΙΑΔΡΟΜΗ'}
=======
DataFrames 914086 and 914632 have different number of columns: 42 vs 43
DataFrames 914086 and 914632 have 1 non-common columns: {'ΔΙΑΔΡΟΜΗ'}
=======
DataFrames 914087 and 914351 have the same number of columns: 43
DataFrames 914087 and 914351 have exactly the same columns
=======
DataFrames 914087 and 914354 have the same number of columns: 43
DataFrames 914087 and 914354 have exactly the same columns
=======
DataFrames 914087 and 914631 have the same number of columns: 43
DataFrames 914087 and 914631 have exactly the same columns
=======
DataFrames 914087 and 914632 have the same number of columns: 43
DataFrames 914087 and 914632 have exactly the same columns
=======
DataFrames 914351 and 914354 have the same number of columns: 43
DataFrames 914351 and 914354 have exactly the same columns
=======
DataFrames 914351 and 914631 have the same number of columns: 43
DataFrames 914351 and 914631 have exactly the same columns
=======
DataFrames 914351 and 914632 have the same number of columns: 43
DataFrames 914351 and 914632 have exactly the same columns
=======
DataFrames 914354 and 914631 have the same number of columns: 43
DataFrames 914354 and 914631 have exactly the same columns
=======
DataFrames 914354 and 914632 have the same number of columns: 43
DataFrames 914354 and 914632 have exactly the same columns
=======
DataFrames 914631 and 914632 have the same number of columns: 43
DataFrames 914631 and 914632 have exactly the same columns
=======

## Empty values

### Remove existing na rows at the bottom

In [60]:
def remove_empty_rows(df):
    return df.dropna(how='all')

for key, df in dfs.items():
    # Remove rows where all values are NaN (completely empty rows)
    df_cleaned = remove_empty_rows(df)
    dfs[key] = df_cleaned
    print(f"DataFrame {key}: Removed {len(df) - len(df_cleaned)} completely empty rows")

DataFrame 914086: Removed 0 completely empty rows
DataFrame 914087: Removed 0 completely empty rows
DataFrame 914351: Removed 0 completely empty rows
DataFrame 914354: Removed 0 completely empty rows
DataFrame 914631: Removed 0 completely empty rows
DataFrame 914632: Removed 0 completely empty rows

### Check null value count in every column

In [76]:
def check_empty_values(df, df_name=None):
    """
    Check for empty/null values in a dataframe and provide detailed information.
    
    Parameters:
    df: pandas DataFrame to check for empty values
    df_name: optional name for the dataframe (for display purposes)
    """
    name = df_name if df_name else "DataFrame"
    
    
    
    print(f"{name}:")
    
    # Get null counts for each column
    null_counts = df.isnull().sum()
    total_nulls = null_counts.sum()
    
    print(f"  Total rows: {len(df)}, Total columns: {len(df.columns)}, Total null values: {total_nulls}")
    
    # Show columns with null values
    columns_with_nulls = null_counts[null_counts > 0]
    all_cols = null_counts[null_counts >= 0]
    non_null_cols = null_counts[null_counts == 0]
    if len(columns_with_nulls) > 0:
        for col, count in all_cols.items():
            percentage = (count / len(df)) * 100
            print(f"    {col}: {count} nulls ({percentage:.1f}%)")
        print(f" {len(non_null_cols)} columns with no nulls: {list(non_null_cols.index)}")
    else:
        print("  No null values found.")
    print("=" * 50)
    
    return non_null_cols
    
# Check empty values for all dataframes
non_null_cols_total = {}
for key, df in dfs.items():
    non_null_cols = check_empty_values(df, key)
    non_null_cols_total[key] = non_null_cols

914086:
  Total rows: 11, Total columns: 42, Total null values: 231
    ΑΡ.ΠΑΡΟΧΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ: 11 nulls (100.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ: 11 nulls (100.0%)
    ΗΜΕΡ.ΛΗΞΕΩΣ: 0 nulls (0.0%)
    ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ: 11 nulls (100.0%)
    ΠΕΡΙΦ.ΓΡΑΦ.: 0 nulls (0.0%)
    ΤΙΜΟΛΟΓΙΟ: 11 nulls (100.0%)
    ΙΔΙΟΚΤΗΤΗΣ: 0 nulls (0.0%)
    ΕΝΟΙΚΟΣ: 0 nulls (0.0%)
    ΔΙΕΥΘΥΝΣΗ: 0 nulls (0.0%)
    ΑΦΜ: 0 nulls (0.0%)
    ΑΡ.ΜΕΤΡΗΤΗ: 11 nulls (100.0%)
    ΔΙΑΜ.: 11 nulls (100.0%)
    ΠΡΟΗΓ.ΕΝΔ.: 0 nulls (0.0%)
    ΠΑΡ.ΕΝΔΕΙΞΗ: 0 nulls (0.0%)
    ΤΕΚΜ.: 0 nulls (0.0%)
    ΤΡΙΜ: 0 nulls (0.0%)
    ΠΡΟΣΘ: 0 nulls (0.0%)
    ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ: 0 nulls (0.0%)
    ΚΥΒΙΚΑ 1: 11 nulls (100.0%)
    ΤΙΜΗΜΑ 1: 11 nulls (100.0%)
    ΚΥΒΙΚΑ 2: 11 nulls (100.0%)
    ΤΙΜΗΜΑ 2: 11 nulls (100.0%)
    ΚΥΒ.3: 11 nulls (100.0%)
    ΤΙΜ.3: 11 nulls (100.0%)
    ΚΥΒ.4: 11 nulls (100.0%)
    ΤΙΜΗΜΑ 4: 11 nulls (100.0%)
    ΚΥΒ.5: 11 nulls (100.0%)
    ΤΙΜΗΜΑ 5: 11 nulls (100.0%)
    ΤΙΜΗΜΑ: 11 nulls (100.0%)
    ΠΑΓΙΟ: 11 nulls (100.0%)
    ΤΕΑΠ: 11 nulls (100.0%)
    ΟΑΠ: 11 nulls (100.0%)
    ΦΠΑ ΤΙΜ.: 0 nulls (0.0%)
    ΦΠΑ ΛΟΙΠΩΝ: 11 nulls (100.0%)
    ΕΡΓΑΣΙΕΣ: 0 nulls (0.0%)
    ΔΙΑΦ.ΚΕΡΜ.: 0 nulls (0.0%)
    ΚΥΡΙΑ ΟΦ.: 0 nulls (0.0%)
    ΠΙΣΤΩΤΙΚΟ: 0 nulls (0.0%)
    ΟΦΕΙΛΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: 0 nulls (0.0%)
    ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ: 0 nulls (0.0%)
 21 columns with no nulls: ['ΑΡ.ΠΑΡΟΧΗΣ', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΕΝΟΙΚΟΣ', 'ΔΙΕΥΘΥΝΣΗ', 'ΑΦΜ', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΤΕΚΜ.', 'ΤΡΙΜ', 'ΠΡΟΣΘ', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ', 'ΦΠΑ ΤΙΜ.', 'ΕΡΓΑΣΙΕΣ', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΚΥΡΙΑ ΟΦ.', 'ΠΙΣΤΩΤΙΚΟ', 'ΟΦΕΙΛΗ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ']
==================================================
914087:
  Total rows: 677, Total columns: 43, Total null values: 9608
    ΔΙΑΔΡΟΜΗ: 245 nulls (36.2%)
    ΑΡ.ΠΑΡΟΧΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ: 245 nulls (36.2%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ: 245 nulls (36.2%)
    ΗΜΕΡ.ΛΗΞΕΩΣ: 0 nulls (0.0%)
    ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ: 245 nulls (36.2%)
    ΠΕΡΙΦ.ΓΡΑΦ.: 0 nulls (0.0%)
    ΤΙΜΟΛΟΓΙΟ: 245 nulls (36.2%)
    ΙΔΙΟΚΤΗΤΗΣ: 0 nulls (0.0%)
    ΕΝΟΙΚΟΣ: 0 nulls (0.0%)
    ΔΙΕΥΘΥΝΣΗ: 0 nulls (0.0%)
    ΑΦΜ: 0 nulls (0.0%)
    ΑΡ.ΜΕΤΡΗΤΗ: 245 nulls (36.2%)
    ΔΙΑΜ.: 245 nulls (36.2%)
    ΠΡΟΗΓ.ΕΝΔ.: 0 nulls (0.0%)
    ΠΑΡ.ΕΝΔΕΙΞΗ: 0 nulls (0.0%)
    ΤΕΚΜ.: 0 nulls (0.0%)
    ΤΡΙΜ: 0 nulls (0.0%)
    ΠΡΟΣΘ: 0 nulls (0.0%)
    ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ: 0 nulls (0.0%)
    ΚΥΒΙΚΑ 1: 266 nulls (39.3%)
    ΤΙΜΗΜΑ 1: 266 nulls (39.3%)
    ΚΥΒΙΚΑ 2: 620 nulls (91.6%)
    ΤΙΜΗΜΑ 2: 620 nulls (91.6%)
    ΚΥΒ.3: 661 nulls (97.6%)
    ΤΙΜ.3: 661 nulls (97.6%)
    ΚΥΒ.4: 670 nulls (99.0%)
    ΤΙΜΗΜΑ 4: 670 nulls (99.0%)
    ΚΥΒ.5: 672 nulls (99.3%)
    ΤΙΜΗΜΑ 5: 672 nulls (99.3%)
    ΤΙΜΗΜΑ: 266 nulls (39.3%)
    ΠΑΓΙΟ: 252 nulls (37.2%)
    ΤΕΑΠ: 638 nulls (94.2%)
    ΟΑΠ: 296 nulls (43.7%)
    ΦΠΑ ΤΙΜ.: 0 nulls (0.0%)
    ΦΠΑ ΛΟΙΠΩΝ: 244 nulls (36.0%)
    ΕΡΓΑΣΙΕΣ: 419 nulls (61.9%)
    ΔΙΑΦ.ΚΕΡΜ.: 0 nulls (0.0%)
    ΚΥΡΙΑ ΟΦ.: 0 nulls (0.0%)
    ΠΙΣΤΩΤΙΚΟ: 0 nulls (0.0%)
    ΟΦΕΙΛΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: 0 nulls (0.0%)
    ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ: 0 nulls (0.0%)
 20 columns with no nulls: ['ΑΡ.ΠΑΡΟΧΗΣ', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΕΝΟΙΚΟΣ', 'ΔΙΕΥΘΥΝΣΗ', 'ΑΦΜ', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΤΕΚΜ.', 'ΤΡΙΜ', 'ΠΡΟΣΘ', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ', 'ΦΠΑ ΤΙΜ.', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΚΥΡΙΑ ΟΦ.', 'ΠΙΣΤΩΤΙΚΟ', 'ΟΦΕΙΛΗ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ']
==================================================
914351:
  Total rows: 26, Total columns: 43, Total null values: 189
    ΔΙΑΔΡΟΜΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΟΧΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ: 0 nulls (0.0%)
    ΗΜΕΡ.ΛΗΞΕΩΣ: 0 nulls (0.0%)
    ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΦ.ΓΡΑΦ.: 0 nulls (0.0%)
    ΤΙΜΟΛΟΓΙΟ: 0 nulls (0.0%)
    ΙΔΙΟΚΤΗΤΗΣ: 0 nulls (0.0%)
    ΕΝΟΙΚΟΣ: 0 nulls (0.0%)
    ΔΙΕΥΘΥΝΣΗ: 0 nulls (0.0%)
    ΑΦΜ: 0 nulls (0.0%)
    ΑΡ.ΜΕΤΡΗΤΗ: 0 nulls (0.0%)
    ΔΙΑΜ.: 0 nulls (0.0%)
    ΠΡΟΗΓ.ΕΝΔ.: 0 nulls (0.0%)
    ΠΑΡ.ΕΝΔΕΙΞΗ: 0 nulls (0.0%)
    ΤΕΚΜ.: 0 nulls (0.0%)
    ΤΡΙΜ: 0 nulls (0.0%)
    ΠΡΟΣΘ: 0 nulls (0.0%)
    ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ: 0 nulls (0.0%)
    ΚΥΒΙΚΑ 1: 1 nulls (3.8%)
    ΤΙΜΗΜΑ 1: 1 nulls (3.8%)
    ΚΥΒΙΚΑ 2: 5 nulls (19.2%)
    ΤΙΜΗΜΑ 2: 5 nulls (19.2%)
    ΚΥΒ.3: 19 nulls (73.1%)
    ΤΙΜ.3: 19 nulls (73.1%)
    ΚΥΒ.4: 21 nulls (80.8%)
    ΤΙΜΗΜΑ 4: 21 nulls (80.8%)
    ΚΥΒ.5: 22 nulls (84.6%)
    ΤΙΜΗΜΑ 5: 22 nulls (84.6%)
    ΤΙΜΗΜΑ: 1 nulls (3.8%)
    ΠΑΓΙΟ: 0 nulls (0.0%)
    ΤΕΑΠ: 26 nulls (100.0%)
    ΟΑΠ: 1 nulls (3.8%)
    ΦΠΑ ΤΙΜ.: 0 nulls (0.0%)
    ΦΠΑ ΛΟΙΠΩΝ: 0 nulls (0.0%)
    ΕΡΓΑΣΙΕΣ: 25 nulls (96.2%)
    ΔΙΑΦ.ΚΕΡΜ.: 0 nulls (0.0%)
    ΚΥΡΙΑ ΟΦ.: 0 nulls (0.0%)
    ΠΙΣΤΩΤΙΚΟ: 0 nulls (0.0%)
    ΟΦΕΙΛΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: 0 nulls (0.0%)
    ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ: 0 nulls (0.0%)
 29 columns with no nulls: ['ΔΙΑΔΡΟΜΗ', 'ΑΡ.ΠΑΡΟΧΗΣ', 'ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ', 'ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΤΙΜΟΛΟΓΙΟ', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΕΝΟΙΚΟΣ', 'ΔΙΕΥΘΥΝΣΗ', 'ΑΦΜ', 'ΑΡ.ΜΕΤΡΗΤΗ', 'ΔΙΑΜ.', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΤΕΚΜ.', 'ΤΡΙΜ', 'ΠΡΟΣΘ', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ', 'ΠΑΓΙΟ', 'ΦΠΑ ΤΙΜ.', 'ΦΠΑ ΛΟΙΠΩΝ', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΚΥΡΙΑ ΟΦ.', 'ΠΙΣΤΩΤΙΚΟ', 'ΟΦΕΙΛΗ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ']
==================================================
914354:
  Total rows: 925, Total columns: 43, Total null values: 15277
    ΔΙΑΔΡΟΜΗ: 517 nulls (55.9%)
    ΑΡ.ΠΑΡΟΧΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ: 516 nulls (55.8%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ: 516 nulls (55.8%)
    ΗΜΕΡ.ΛΗΞΕΩΣ: 0 nulls (0.0%)
    ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ: 516 nulls (55.8%)
    ΠΕΡΙΦ.ΓΡΑΦ.: 0 nulls (0.0%)
    ΤΙΜΟΛΟΓΙΟ: 516 nulls (55.8%)
    ΙΔΙΟΚΤΗΤΗΣ: 0 nulls (0.0%)
    ΕΝΟΙΚΟΣ: 0 nulls (0.0%)
    ΔΙΕΥΘΥΝΣΗ: 0 nulls (0.0%)
    ΑΦΜ: 0 nulls (0.0%)
    ΑΡ.ΜΕΤΡΗΤΗ: 517 nulls (55.9%)
    ΔΙΑΜ.: 516 nulls (55.8%)
    ΠΡΟΗΓ.ΕΝΔ.: 0 nulls (0.0%)
    ΠΑΡ.ΕΝΔΕΙΞΗ: 0 nulls (0.0%)
    ΤΕΚΜ.: 0 nulls (0.0%)
    ΤΡΙΜ: 0 nulls (0.0%)
    ΠΡΟΣΘ: 0 nulls (0.0%)
    ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ: 0 nulls (0.0%)
    ΚΥΒΙΚΑ 1: 593 nulls (64.1%)
    ΤΙΜΗΜΑ 1: 593 nulls (64.1%)
    ΚΥΒΙΚΑ 2: 806 nulls (87.1%)
    ΤΙΜΗΜΑ 2: 806 nulls (87.1%)
    ΚΥΒ.3: 848 nulls (91.7%)
    ΤΙΜ.3: 848 nulls (91.7%)
    ΚΥΒ.4: 888 nulls (96.0%)
    ΤΙΜΗΜΑ 4: 888 nulls (96.0%)
    ΚΥΒ.5: 915 nulls (98.9%)
    ΤΙΜΗΜΑ 5: 915 nulls (98.9%)
    ΤΙΜΗΜΑ: 593 nulls (64.1%)
    ΠΑΓΙΟ: 516 nulls (55.8%)
    ΤΕΑΠ: 909 nulls (98.3%)
    ΟΑΠ: 625 nulls (67.6%)
    ΦΠΑ ΤΙΜ.: 0 nulls (0.0%)
    ΦΠΑ ΛΟΙΠΩΝ: 515 nulls (55.7%)
    ΕΡΓΑΣΙΕΣ: 405 nulls (43.8%)
    ΔΙΑΦ.ΚΕΡΜ.: 0 nulls (0.0%)
    ΚΥΡΙΑ ΟΦ.: 0 nulls (0.0%)
    ΠΙΣΤΩΤΙΚΟ: 0 nulls (0.0%)
    ΟΦΕΙΛΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: 0 nulls (0.0%)
    ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ: 0 nulls (0.0%)
 20 columns with no nulls: ['ΑΡ.ΠΑΡΟΧΗΣ', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΕΝΟΙΚΟΣ', 'ΔΙΕΥΘΥΝΣΗ', 'ΑΦΜ', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΤΕΚΜ.', 'ΤΡΙΜ', 'ΠΡΟΣΘ', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ', 'ΦΠΑ ΤΙΜ.', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΚΥΡΙΑ ΟΦ.', 'ΠΙΣΤΩΤΙΚΟ', 'ΟΦΕΙΛΗ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ']
==================================================
914631:
  Total rows: 40, Total columns: 43, Total null values: 650
    ΔΙΑΔΡΟΜΗ: 23 nulls (57.5%)
    ΑΡ.ΠΑΡΟΧΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ: 23 nulls (57.5%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ: 23 nulls (57.5%)
    ΗΜΕΡ.ΛΗΞΕΩΣ: 0 nulls (0.0%)
    ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ: 23 nulls (57.5%)
    ΠΕΡΙΦ.ΓΡΑΦ.: 0 nulls (0.0%)
    ΤΙΜΟΛΟΓΙΟ: 23 nulls (57.5%)
    ΙΔΙΟΚΤΗΤΗΣ: 0 nulls (0.0%)
    ΕΝΟΙΚΟΣ: 0 nulls (0.0%)
    ΔΙΕΥΘΥΝΣΗ: 0 nulls (0.0%)
    ΑΦΜ: 0 nulls (0.0%)
    ΑΡ.ΜΕΤΡΗΤΗ: 23 nulls (57.5%)
    ΔΙΑΜ.: 23 nulls (57.5%)
    ΠΡΟΗΓ.ΕΝΔ.: 0 nulls (0.0%)
    ΠΑΡ.ΕΝΔΕΙΞΗ: 0 nulls (0.0%)
    ΤΕΚΜ.: 0 nulls (0.0%)
    ΤΡΙΜ: 0 nulls (0.0%)
    ΠΡΟΣΘ: 0 nulls (0.0%)
    ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ: 0 nulls (0.0%)
    ΚΥΒΙΚΑ 1: 24 nulls (60.0%)
    ΤΙΜΗΜΑ 1: 24 nulls (60.0%)
    ΚΥΒΙΚΑ 2: 31 nulls (77.5%)
    ΤΙΜΗΜΑ 2: 31 nulls (77.5%)
    ΚΥΒ.3: 38 nulls (95.0%)
    ΤΙΜ.3: 38 nulls (95.0%)
    ΚΥΒ.4: 38 nulls (95.0%)
    ΤΙΜΗΜΑ 4: 38 nulls (95.0%)
    ΚΥΒ.5: 38 nulls (95.0%)
    ΤΙΜΗΜΑ 5: 38 nulls (95.0%)
    ΤΙΜΗΜΑ: 24 nulls (60.0%)
    ΠΑΓΙΟ: 23 nulls (57.5%)
    ΤΕΑΠ: 40 nulls (100.0%)
    ΟΑΠ: 24 nulls (60.0%)
    ΦΠΑ ΤΙΜ.: 0 nulls (0.0%)
    ΦΠΑ ΛΟΙΠΩΝ: 23 nulls (57.5%)
    ΕΡΓΑΣΙΕΣ: 17 nulls (42.5%)
    ΔΙΑΦ.ΚΕΡΜ.: 0 nulls (0.0%)
    ΚΥΡΙΑ ΟΦ.: 0 nulls (0.0%)
    ΠΙΣΤΩΤΙΚΟ: 0 nulls (0.0%)
    ΟΦΕΙΛΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: 0 nulls (0.0%)
    ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ: 0 nulls (0.0%)
 20 columns with no nulls: ['ΑΡ.ΠΑΡΟΧΗΣ', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΕΝΟΙΚΟΣ', 'ΔΙΕΥΘΥΝΣΗ', 'ΑΦΜ', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΤΕΚΜ.', 'ΤΡΙΜ', 'ΠΡΟΣΘ', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ', 'ΦΠΑ ΤΙΜ.', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΚΥΡΙΑ ΟΦ.', 'ΠΙΣΤΩΤΙΚΟ', 'ΟΦΕΙΛΗ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ']
==================================================
914632:
  Total rows: 480, Total columns: 43, Total null values: 8286
    ΔΙΑΔΡΟΜΗ: 273 nulls (56.9%)
    ΑΡ.ΠΑΡΟΧΗΣ: 0 nulls (0.0%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ: 272 nulls (56.7%)
    ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ: 272 nulls (56.7%)
    ΗΜΕΡ.ΛΗΞΕΩΣ: 0 nulls (0.0%)
    ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ: 272 nulls (56.7%)
    ΠΕΡΙΦ.ΓΡΑΦ.: 0 nulls (0.0%)
    ΤΙΜΟΛΟΓΙΟ: 272 nulls (56.7%)
    ΙΔΙΟΚΤΗΤΗΣ: 0 nulls (0.0%)
    ΕΝΟΙΚΟΣ: 0 nulls (0.0%)
    ΔΙΕΥΘΥΝΣΗ: 0 nulls (0.0%)
    ΑΦΜ: 0 nulls (0.0%)
    ΑΡ.ΜΕΤΡΗΤΗ: 273 nulls (56.9%)
    ΔΙΑΜ.: 272 nulls (56.7%)
    ΠΡΟΗΓ.ΕΝΔ.: 0 nulls (0.0%)
    ΠΑΡ.ΕΝΔΕΙΞΗ: 0 nulls (0.0%)
    ΤΕΚΜ.: 0 nulls (0.0%)
    ΤΡΙΜ: 0 nulls (0.0%)
    ΠΡΟΣΘ: 0 nulls (0.0%)
    ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ: 0 nulls (0.0%)
    ΚΥΒΙΚΑ 1: 348 nulls (72.5%)
    ΤΙΜΗΜΑ 1: 348 nulls (72.5%)
    ΚΥΒΙΚΑ 2: 455 nulls (94.8%)
    ΤΙΜΗΜΑ 2: 455 nulls (94.8%)
    ΚΥΒ.3: 472 nulls (98.3%)
    ΤΙΜ.3: 472 nulls (98.3%)
    ΚΥΒ.4: 474 nulls (98.8%)
    ΤΙΜΗΜΑ 4: 474 nulls (98.8%)
    ΚΥΒ.5: 476 nulls (99.2%)
    ΤΙΜΗΜΑ 5: 476 nulls (99.2%)
    ΤΙΜΗΜΑ: 348 nulls (72.5%)
    ΠΑΓΙΟ: 272 nulls (56.7%)
    ΤΕΑΠ: 480 nulls (100.0%)
    ΟΑΠ: 351 nulls (73.1%)
    ΦΠΑ ΤΙΜ.: 0 nulls (0.0%)
    ΦΠΑ ΛΟΙΠΩΝ: 272 nulls (56.7%)
    ΕΡΓΑΣΙΕΣ: 207 nulls (43.1%)
    ΔΙΑΦ.ΚΕΡΜ.: 0 nulls (0.0%)
    ΚΥΡΙΑ ΟΦ.: 0 nulls (0.0%)
    ΠΙΣΤΩΤΙΚΟ: 0 nulls (0.0%)
    ΟΦΕΙΛΗ: 0 nulls (0.0%)
    ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: 0 nulls (0.0%)
    ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ: 0 nulls (0.0%)
 20 columns with no nulls: ['ΑΡ.ΠΑΡΟΧΗΣ', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΕΝΟΙΚΟΣ', 'ΔΙΕΥΘΥΝΣΗ', 'ΑΦΜ', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΤΕΚΜ.', 'ΤΡΙΜ', 'ΠΡΟΣΘ', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ', 'ΦΠΑ ΤΙΜ.', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΚΥΡΙΑ ΟΦ.', 'ΠΙΣΤΩΤΙΚΟ', 'ΟΦΕΙΛΗ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ']
==================================================

### Find from existing 6 files, the columns without NA values

In [87]:
# Also show columns with no null values that are common to all dataframes
common_non_null_columns = set.intersection(*[set(non_null_cols.index) for non_null_cols in non_null_cols_total.values()])
print(f"\nCommon columns with no null values across all dataframes ({len(common_non_null_columns)} total):")
common_non_null_columns = list(common_non_null_columns)
print(common_non_null_columns)

Common columns with no null values across all dataframes (20 total):
['ΑΡ.ΠΑΡΟΧΗΣ', 'ΚΥΡΙΑ ΟΦ.', 'ΕΝΟΙΚΟΣ', 'ΠΑΡ.ΕΝΔΕΙΞΗ', 'ΑΦΜ', 'ΠΙΣΤΩΤΙΚΟ', 'ΙΔΙΟΚΤΗΤΗΣ', 'ΔΙΑΦ.ΚΕΡΜ.', 'ΠΡΟΣΘ', 'ΦΠΑ ΤΙΜ.', 'ΗΜΕΡ.ΛΗΞΕΩΣ', 'ΟΦΕΙΛΗ', 'ΠΕΡΙΦ.ΓΡΑΦ.', 'ΤΕΚΜ.', 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ', 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ', 'ΔΙΕΥΘΥΝΣΗ', 'ΤΡΙΜ', 'ΠΡΟΗΓ.ΕΝΔ.', 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ']

In [88]:
common_non_null_columns

['ΑΡ.ΠΑΡΟΧΗΣ',
 'ΚΥΡΙΑ ΟΦ.',
 'ΕΝΟΙΚΟΣ',
 'ΠΑΡ.ΕΝΔΕΙΞΗ',
 'ΑΦΜ',
 'ΠΙΣΤΩΤΙΚΟ',
 'ΙΔΙΟΚΤΗΤΗΣ',
 'ΔΙΑΦ.ΚΕΡΜ.',
 'ΠΡΟΣΘ',
 'ΦΠΑ ΤΙΜ.',
 'ΗΜΕΡ.ΛΗΞΕΩΣ',
 'ΟΦΕΙΛΗ',
 'ΠΕΡΙΦ.ΓΡΑΦ.',
 'ΤΕΚΜ.',
 'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ',
 'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ',
 'ΔΙΕΥΘΥΝΣΗ',
 'ΤΡΙΜ',
 'ΠΡΟΗΓ.ΕΝΔ.',
 'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ']

### function that checks for empty values in the rows that must be filled

In [90]:
filled_cols = [
    'ΑΡ.ΠΑΡΟΧΗΣ',
    'ΚΥΡΙΑ ΟΦ.',
    'ΕΝΟΙΚΟΣ',
    'ΠΑΡ.ΕΝΔΕΙΞΗ',
    'ΑΦΜ',
    'ΠΙΣΤΩΤΙΚΟ',
    'ΙΔΙΟΚΤΗΤΗΣ',
    'ΔΙΑΦ.ΚΕΡΜ.',
    'ΠΡΟΣΘ',
    'ΦΠΑ ΤΙΜ.',
    'ΗΜΕΡ.ΛΗΞΕΩΣ',
    'ΟΦΕΙΛΗ',
    'ΠΕΡΙΦ.ΓΡΑΦ.',
    'ΤΕΚΜ.',
    'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ',
    'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ',
    'ΔΙΕΥΘΥΝΣΗ',
    'ΤΡΙΜ',
    'ΠΡΟΗΓ.ΕΝΔ.',
    'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ'
]

In [91]:
def check_filled_columns(df, required_columns, df_name=None):
    """
    Check if the specified columns in the dataframe are completely filled (no nulls).
    
    Parameters:
    df: pandas DataFrame to check
    required_columns: list of column names that must be completely filled
    df_name: optional name for the dataframe (for display purposes)
    """
    name = df_name if df_name else "DataFrame"
    print(f"Checking required columns in {name}:")
    
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        print(f"  Missing columns: {missing_columns}")
        return False
    
    unfilled_columns = []
    for col in required_columns:
        if df[col].isnull().any():
            unfilled_columns.append(col)
    
    if unfilled_columns:
        print(f"  Columns with missing values: {unfilled_columns}")
        return False
    else:
        print("  All required columns are completely filled.")
        return True

for key, df in dfs.items():
    check_filled_columns(df, filled_cols, df_name=key)

Checking required columns in 914086:
  All required columns are completely filled.
Checking required columns in 914087:
  All required columns are completely filled.
Checking required columns in 914351:
  All required columns are completely filled.
Checking required columns in 914354:
  All required columns are completely filled.
Checking required columns in 914631:
  All required columns are completely filled.
Checking required columns in 914632:
  All required columns are completely filled.

## Duplicates

### Duplicate rows

In [106]:
def check_duplicates_rows(df, df_name=None, cols="all"):
    """
    Check for duplicate rows in a dataframe and provide detailed information.
    
    Parameters:
    df: pandas DataFrame to check for duplicates
    df_name: optional name for the dataframe (for display purposes)
    
    Returns:
    dict with duplicate information
    """
    name = df_name if df_name else "DataFrame"
    if cols == "all":
        cols = df.columns.tolist()
        
    # Check for duplicates
    duplicates = df[cols].duplicated()
    num_duplicates = duplicates.sum()
    
    # Get duplicate rows
    duplicate_rows = df[duplicates]
    
    # Check for duplicates keeping all occurrences
    all_duplicates = df[df.duplicated(keep=False)]
    
    print(f"{name}:")
    print(f"  Duplicate rows: {num_duplicates}/{len(df)}")
    # print(f"  Unique rows: {len(df) - num_duplicates}")
    
    if num_duplicates > 0:
        print(f"  Rows involved in duplicates (including originals): {len(all_duplicates)}")
        print(f"  Duplicate row indices: {duplicate_rows.index.tolist()}")
        
        # Show first few duplicate rows
        if len(duplicate_rows) > 0:
            print(f"  First duplicate row(s):")
            print(duplicate_rows.head())
    
    print("=" * 50)
    
    # return {
    #     'total_rows': len(df),
    #     'duplicate_count': num_duplicates,
    #     'unique_count': len(df) - num_duplicates,
    #     'duplicate_indices': duplicate_rows.index.tolist(),
    #     'duplicate_rows': duplicate_rows
    # }

# Check duplicates for all dataframes
for key, df in dfs.items():
    check_duplicates_rows(df, key, cols="all")

914086:
  Duplicate rows: 0/11
==================================================
914087:
  Duplicate rows: 0/677
==================================================
914351:
  Duplicate rows: 0/26
==================================================
914354:
  Duplicate rows: 0/925
==================================================
914631:
  Duplicate rows: 0/40
==================================================
914632:
  Duplicate rows: 0/480
==================================================

### Duplicate ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ (invoice number)

In [ ]:
for key, df in dfs.items():
    check_duplicates_rows(df, df_name=key, cols='ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ')

914086:
  Duplicate rows: 0/11
==================================================
914087:
  Duplicate rows: 0/677
==================================================
914351:
  Duplicate rows: 0/26
==================================================
914354:
  Duplicate rows: 0/925
==================================================
914631:
  Duplicate rows: 0/40
==================================================
914632:
  Duplicate rows: 0/480
==================================================

## ΣΥΓΚΡΙΤΙΚΟ

In [146]:
# dfs['914632'].columns.tolist()

In [126]:
cols_needed = [
    'ΔΙΑΔΡΟΜΗ',
    'ΑΡ.ΠΑΡΟΧΗΣ',
    'ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ',
    'ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ',
    'ΗΜΕΡ.ΛΗΞΕΩΣ',
    'ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ',
    'ΠΕΡΙΦ.ΓΡΑΦ.',
    'ΤΙΜΟΛΟΓΙΟ',
    'ΙΔΙΟΚΤΗΤΗΣ',
    'ΕΝΟΙΚΟΣ',
    'ΔΙΕΥΘΥΝΣΗ',
    'ΑΦΜ',
    'ΑΡ.ΜΕΤΡΗΤΗ',
    'ΔΙΑΜ.',
    'ΠΡΟΗΓ.ΕΝΔ.',
    'ΠΑΡ.ΕΝΔΕΙΞΗ',
    'ΤΕΚΜ.',
    'ΤΡΙΜ',
    'ΠΡΟΣΘ',
    'ΤΥΠΟΣ ΛΟΓΑΡΙΑΣΜΟΥ',
    'ΚΥΒΙΚΑ 1',
    'ΤΙΜΗΜΑ 1',
    'ΚΥΒΙΚΑ 2',
    'ΤΙΜΗΜΑ 2',
    'ΚΥΒ.3',
    'ΤΙΜ.3',
    'ΚΥΒ.4',
    'ΤΙΜΗΜΑ 4',
    'ΚΥΒ.5',
    'ΤΙΜΗΜΑ 5',
    'ΤΙΜΗΜΑ',
    'ΠΑΓΙΟ',
    'ΤΕΑΠ',
    'ΟΑΠ',
    'ΦΠΑ ΤΙΜ.',
    'ΦΠΑ ΛΟΙΠΩΝ',
    'ΕΡΓΑΣΙΕΣ',
    'ΔΙΑΦ.ΚΕΡΜ.',
    'ΚΥΡΙΑ ΟΦ.',
    'ΠΙΣΤΩΤΙΚΟ',
    'ΟΦΕΙΛΗ',
    'ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ',
    'ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ'
    ]

In [145]:
# Compare ΣΥΓΚΡΙΤΙΚΟΣ ΕΥΔΑΠ 02.10.2025.xlsx with 914632.xlsx
df1 = pd.read_excel("../" + datapath + "ΣΥΓΚΡΙΤΙΚΟΣ ΕΥΔΑΠ 02.10.2025.xlsx", sheet_name="ΠΟΛΛΑΠΛΟΣ 08.09.2025")
df1 = df1[cols_needed].copy() # keep original file columsn, without the pivot table
num_rows_df1 = df1['ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ'].nunique()
df1 = df1.iloc[:num_rows_df1]
df2 = dfs['914632'].copy()

df1.shape, df2.shape

((480, 43), (480, 43))

In [ ]:
df1.compare(df2,)

False

## ΒΑΣΗ

In [42]:
for key, df in dfs.items():
    print(f"{key}: {df['ΙΔΙΟΚΤΗΤΗΣ'].unique()}")
    print("===")

914086: ['ΤΡΑΠΕΖΑ  EUROBANK A.E.' 'ΚΟΙΤΣΑΝΟΥ ΦΩΤΕΙΝΗ' 'ΔΕΣΠΟΤΑΚΗΣ ΖΑΧΑΡΙΑΣ' nan]
===
914087: ['ΤΡΑΠΕΖΑ  EUROBANK A.E.' 'ΚΟΝΣΟΥΛΑΣ ΙΩΑΝΝΗΣ             00'
 'ΚΟΝΣΟΥΛΑΣ ΠΑΝΑΓΙΩΤΗΣ Ε.Π.Ε' 'ΔΑΝΙΗΛ ΑΓΛΑΪΑ & ΛΟΙΠΟΙ ΣΥΝΙΔΙΟΚΤ'
 'ΕΜΠΕΙΡΙΚΟΣ ΛΕΩΝΙΔΑΣ' 'ΤΖΑΝΕΤΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ' 'ΚΑΛΟΓΕΡΟΠΟΥΛΟΣ ΠΑΝΑΓΙΩΤΗΣ'
 'ΤΖΟΥΜΑΚΗΣ ΧΑΡΙΛΑΟΣ' 'ΣΚΡΙΒΑΝΟΥ ΠΑΡΑΣΚΕΥΗ'
 'ΜΥΛΩΝΑΣ ΙΩΑΝΝΗΣ & ΛΟΙΠΟΙ ΣΥΝΙΔ' 'Ε. ΣΠΑΘΑΡΙΩΤΗ ΑΕ'
 'ΜΠΑΡΑΜΠΟΥΤΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ' 'ΓΚΕΛΛΑΣ ΧΡΗΣΤΟΣ' 'ΜΙΧΑΣ ΑΡΙΣΤΕΙΔΗΣ'
 'ΓΕΩΡΓΑΚΗΣ ΔΗΜΟΣΘ & ΛΟΙΠΟΙ ΣΥΝΙΔ' 'ΓΚΑΤΖΩΝΗΣ ΑΝΤΩΝΗΣ ΚΛΠ ΣΥΝΙΔ'
 'ΠΡΩΤΟΓΕΡΟΣ ΘΩΜΑΣ' 'ΙΩΣΗΦ ΓΟΥΜΕΝΑΚΗΣ & ΣΙΑ Ε.Ε.' 'KAZEMI ELZA'
 'Κ ΓΑΛΑΝΟΣ ΚΑΙ ΣΙΑ ΕΤΕΕ' 'ΞΑΓΟΡΑΡΗΣ ΓΡΗΓΟΡΙΟΣ' 'ΣΤΑΜΟΣ ΣΤΥΛΙΑΝΟΣ'
 'ΓΟΥΛΑ ΦΙΛΙΩ & ΑΘΑΝΑΣΙΟΣ' 'ΓΟΥΛΑ ΦΙΛΙΩ' 'ΔΙΓΑΛΑΚΗΣ ΠΑΝΑΓΙΩΤΗΣ'
 'ΜΑΜΜΕΑΣ ΗΛΙΑΣ' 'ΑΝΑΓΝΩΣΤΟΠΟΥΛΟΣ ΑΘΑΝ, ΝΙΚ ΚΛΠ' 'ΠΗΛΙΧΟΣ ΣΠΥΡΙΔΩΝ'
 'ΑΘΑΝΑΣΟΠΟΥΛΟΣ ΙΩΑΝΝΗΣ' 'ΑΝΔΡΙΤΣΑΚΗ ΑΝΝΑ-ΛΟΥΚΙΑ'
 'BRACER INVESTMENT PROPERTIES IV ΜΟΝΟΠΡΟΣΩΠΗ Α.Ε.'
 'ΠΑΠΑΔΟΠΟΥΛΟΣ ΝΙΚΟΛΑΟΣ ΚΛΠ ΣΥΝΙΔ' 'ΤΕΧΝΟΔΟΜΙΚΗ Α Ε' 'ΔΡΥΜΠΕΤΗ ΗΛΕΚΤΡΑ'
 'ΠΑΝ.Ι.ΓΚΙΚΑ & ΠΑΡΑΣ.ΓΚΙΚΑ' 'ΚΑΠΕΤΑΝΙΟΥ ΑΙΚΑΤΕΡΙΝΗ'
 'ΜΑΥΡΟΜΙΧΑΛΗΣ ΜΙΧΑΗΛ & ΛΟΙΠΟΙ ΣΥΝ' 'ΜΑΡΟΥΓΚΑ ΒΑΣΙΛΙΚΟΥΛΑ'
 'ΛΙΑΚΑΚΟΥ ΕΛΕΝΗ' 'ΖΑΧΑΡΟΠΟΥΛΟΣ ΝΙΚΟΛΑΟΣ' 'ΔΗΜΑΡΑΣ ΓΕΩΡΓΙΟΣ'
 'ΓΕΩΡΓΙΟΥ ΓΕΩΡΓΙΟΣ' 'ΚΟΥΤΣΟΓΙΑΝΝΗΣ ΔΙΟΝΥΣΙΟΣ ΤΟΥ ΛΕΩΝ'
 'ΣΑΣΣΑΛΟΥ ΣΟΦΙΑ & ΛΟΙΠΟΙ ΣΥΝΙΔ' 'ΣΑΣΣΑΛΟΥ ΣΟΦΙΑ'
 'ΓΑΒΑΛΑΚΗ ΕΥΓΕΝΙΑ ΚΛΠ ΣΥΝΙΔΙΟΚΤ.' 'ΜΥΤΙΛΗΝΑΙΟΥ ΣΜΑΡΑΓΔΑ'
 'Δ. ΚΡΑΣΣΑΣ-Κ. ΠΟΛΥΚΡΕΤΗΣ ΚΟΙΝΟΠΡΑΞΙΑ' 'ΧΑΤΖΗΪΩΑΚΕΙΜΙΔΗΣ ΗΡΑΚΛΗΣ'
 'ΧΑΤΖΗΙΩΑΚΕΙΜΙΔΗ ΕΥΘΥΜΙΑ' 'ΞΕΝΑΡΙΟΣ ΣΤΕΦΑΝΟΣ' 'ΠΑΠΑΤΕΣΤΑ ΜΑΡΙΑ-ΕΛΕΝΗ'
 'ΤΣΙΤΣΙΛΙΑΝΟΥ ΕΥΓΕΝΙΑ' 'ΔΙΑΚΑΚΗ ΕΥΓΕΝΙΑ & ΛΟΙΠΟΙ ΣΥΝΙΔ'
 'ΔΙΑΚΑΚΗ ΕΥΓΕΝ. & ΛΟΙΠΟΙ ΣΥΝΙΔΙΟΚ' 'ΖΑΡΟΚΩΣΤΑΣ ΝΙΚΟΛΑΟΣ'
 'ΓΙΑΝΙΤΣΗ ΣΤΑΜΑΤΙΑ             00' 'ΓΚΙΓΚΙΛΙΝΗΣ ΜΙΧΑΗΛ' nan]
===
914351: ['ΤΡΑΠΕΖΑ  EUROBANK A.E.' nan]
===
914354: ['ΜΕΤΟΧ ΤΑΜΕΙΟ ΠΟΛΙΤΙΚΩΝ ΥΠΑΛΛΗΛΩΝ' 'ΤΡΑΠΕΖΑ  EUROBANK A.E.'
 'ΜΠΟΤΣΑΡΗ ΠΗΝΕΛΟΠΗ ΕΛΕΝΗ' 'ΑΚΑΔΗΜΙΑ ΑΘΗΝΩΝ ΕΓΓΟΝΟΠΟΥΛΟΣ Κ00'
 'ΙΔΡΥΜΑ ΕΥΓΕΝΙΔΟΥ              00' 'ΕΘΝΙΚΟΝ ΙΔΡΥΜΑ ΕΡΕΥΝΩΝ        00'
 'ΟΥΡΑΝΗ ΕΛΕΝΗ                  00' 'ΑΥΣΤΡΙΑΚΕΣ ΑΕΡΟΠΟΡΙΚΕΣ ΓΡΑΜΜΕΣ00'
 'ΔΗΜΙΟΥΡΓΙΑ ΑΝ ΚΤΗΜ ΤΕΧΝ ΕΤΑΙ  00' 'ΣΠΑΘΑΚΗΣ-ΝΙΩΡΑΣ- ΓΙΑΤΡΑ ΟΕ'
 'ΒΛΑΧΟΥΛΗ-ΚΑΡΕΛΑ ΧΡΙΣΤΙΝΑ' 'EUROBANK - ΔΙΑΚΟΝΟΥ-ΦΩΤΟΠΟΥΛΟΥ'
 'ΔΕΛΗΟΛΑΝΗΣ ΙΩΑΝ.& ΔΕΛΗΟΛΑΝΗ ΠΟΛ.' 'ΞΕΝΟΣ Γ.ΞΕΝΟΥ ΑΙΚΑΤΕΡ.& ΑΦΡΟΔΙΤΗ'
 'ΕΒΟ ΑΕ ΕΜΠΟΡΙΟ-ΒΙΟΜΗΧ.-ΟΙΚΟΔΟΜΕΣ' 'ΔΑΝΙΗΛ ΑΓΛΑΪΑ & ΛΟΙΠΟΙ ΣΥΝΙΔΙΟΚΤ'
 'ΕΜΠΕΙΡΙΚΟΣ ΛΕΩΝΙΔΑΣ' 'ΤΖΑΝΕΤΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ' 'ΠΡΟΝΤΕΑ Α.Ε.Ε.Α.Π'
 'ΑΓΓΕΛΟΠΟΥΛΟΣ ΠΑΥΛΟΣ' 'ΚΟΝΤΙΖΑΣ ΓΕΩΡΓΙΟΣ' 'ΔΑΒΒΕΤΑ ΓΕΩΡΓΙΑ ΚΛΠ'
 'ΛΙΒΑ ΓΕΩΡΓΟΥΝΤΖΟΥ ΑΙΚΑΤΕΡΙΝΗ' 'Ε. ΣΠΑΘΑΡΙΩΤΗ ΑΕ'
 'ΜΠΑΡΑΜΠΟΥΤΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ' 'ΣΤΕΦΑΝΟΥ ΓΕΩΡΓ' 'ΜΑΝΤΖΟΥΡΙΔΗΣ ΣΩΤΗΡΙΟΣ'
 'ΠΟΥΛΑΚΑΚΟΥ ΑΙΚΑΤΕΡΙΝΗ' 'ΜΑΝΤΖΑΡΗΣ ΔΗΜΗΤΡΙΟΣ'
 'ΙΝΤΕΡΑΜΕΡΙΚΑΝ ΕΛΛΗΝΙΚΗ ΑΣΦΑΛΙΣΤΙΚΗ ΑΝΩΝΥΜΗ ΕΤΑΙΡΙΑ' 'KAZEMI ELZA'
 'Κ ΓΑΛΑΝΟΣ ΚΑΙ ΣΙΑ ΕΤΕΕ' 'ΞΑΓΟΡΑΡΗΣ ΓΡΗΓΟΡΙΟΣ' 'ΣΤΑΜΟΣ ΣΤΥΛΙΑΝΟΣ'
 'ΓΟΥΛΑ ΦΙΛΙΩ & ΑΘΑΝΑΣΙΟΣ' 'ΓΟΥΛΑ ΦΙΛΙΩ' 'ΤΣΟΥΜΑΣ ΠΕΤΡΟΣ ΚΛΠ ΣΥΝΙΔ'
 'ΧΑΛΚΙΔΗΣ ΣΤΑΥΡΟΣ' 'ΠΗΛΙΧΟΣ ΣΠΥΡΙΔΩΝ' 'ΣΚΑΦΙΔΑΚΗΣ ΝΙΚ & ΛΟΙΠΟΙ ΣΥΝΙΔ'
 'ΠΑΠΑΒΑΣΙΛΕΙΟΥ ΑΝΤΩΝΙΟΣ' 'ΑΝΔΡΙΤΣΑΚΗ ΑΝΝΑ-ΛΟΥΚΙΑ'
 'ΠΑΠΑΔΟΠΟΥΛΟΣ ΝΙΚΟΛΑΟΣ ΚΛΠ ΣΥΝΙΔ' 'QEVANI ARTAN' 'ΤΕΧΝΟΔΟΜΙΚΗ Α Ε'
 'ΜΑΡΟΥΓΚΑ ΒΑΣΙΛΙΚΟΥΛΑ' 'ΛΙΑΚΑΚΟΥ ΕΛΕΝΗ' 'Γ  ΝΟΙΚΟΚΥΡΑΚΗ ΚΑΙ ΣΙΑ ΟΕ'
 'ΚΑΛΥΨΩ ΑΕΒΕ                   00' 'ΚΑΤΣΑΡΟΣ ΝΙΚΟΛΑΟΣ'
 'ΠΑΠΑΔΑΚΗΣ ΓΕΩΡΓΙΟΣ' 'ΛΟΥΠΑΣΑΚΗΣ-ΛΟΥΠΑΣΗΣ ΠΑΝΑΓΙΩΤΗΣ'
 'ΒΟΥΛΓΟΥΡΙΔΗ ΠΑΡΑΣΚΕΥΗ' 'ΚΑΛΠΙΔΟΥ ΣΟΦΙΑ'
 'Δ. ΚΡΑΣΣΑΣ-Κ. ΠΟΛΥΚΡΕΤΗΣ ΚΟΙΝΟΠΡΑΞΙΑ' 'ΖΑΡΟΚΩΣΤΑΣ ΝΙΚΟΛΑΟΣ'
 'ΓΙΑΝΙΤΣΗ ΣΤΑΜΑΤΙΑ             00' 'ΓΚΙΓΚΙΛΙΝΗΣ ΜΙΧΑΗΛ'
 'ΛΟΓΟΘΕΤΗΣ ΝΙΚ ΗΡΑΚΛ ΜΕΣΣΗΝΗΣ Θ Α' 'ΛΟΓΟΘΕΤΗΣ ΗΡΑΚΛΗΣ & ΛΟΙΠΟΙ ΣΥΝΙΔ'
 'ΤΣΙΓΚΟΣ ΔΗΜΗΤΡΗΣ & ΙΣΙΔΩΡΟΣ' nan]
===
914631: ['ΤΡΑΠΕΖΑ  EUROBANK A.E.' 'ΚΟΙΤΣΑΝΟΥ ΦΩΤΕΙΝΗ' 'ΔΕΣΠΟΤΑΚΗΣ ΖΑΧΑΡΙΑΣ'
 'LAMDA ESTATE DEVELOPMENT S.A.' nan]
===
914632: ['ΜΕΤΟΧ ΤΑΜΕΙΟ ΠΟΛΙΤΙΚΩΝ ΥΠΑΛΛΗΛΩΝ' 'ΤΡΑΠΕΖΑ  EUROBANK A.E.'
 'ΜΠΟΤΣΑΡΗ ΠΗΝΕΛΟΠΗ ΕΛΕΝΗ' 'ΑΚΑΔΗΜΙΑ ΑΘΗΝΩΝ ΕΓΓΟΝΟΠΟΥΛΟΣ Κ00'
 'ΙΔΡΥΜΑ ΕΥΓΕΝΙΔΟΥ              00' 'ΕΘΝΙΚΟΝ ΙΔΡΥΜΑ ΕΡΕΥΝΩΝ        00'
 'ΟΥΡΑΝΗ ΕΛΕΝΗ                  00' 'ΑΥΣΤΡΙΑΚΕΣ ΑΕΡΟΠΟΡΙΚΕΣ ΓΡΑΜΜΕΣ00'
 'ΔΗΜΙΟΥΡΓΙΑ ΑΝ ΚΤΗΜ ΤΕΧΝ ΕΤΑΙ  00' 'ΣΠΑΘΑΚΗΣ-ΝΙΩΡΑΣ- ΓΙΑΤΡΑ ΟΕ'
 'ΒΛΑΧΟΥΛΗ-ΚΑΡΕΛΑ ΧΡΙΣΤΙΝΑ' 'ΚΟΝΣΟΥΛΑΣ ΙΩΑΝΝΗΣ             00'
 'ΚΟΝΣΟΥΛΑΣ ΠΑΝΑΓΙΩΤΗΣ Ε.Π.Ε' 'ΝΕΟΦΩΤΙΣΤΟΣ ΔΗΜ. & ΠΑΝΩΡΑΙΑ'
 'ΑΓΓΕΛΟΠΟΥΛΟΣ ΠΑΥΛΟΣ' 'ΔΑΒΒΕΤΑ ΓΕΩΡΓΙΑ ΚΛΠ'
 'ΛΙΒΑ ΓΕΩΡΓΟΥΝΤΖΟΥ ΑΙΚΑΤΕΡΙΝΗ' 'ΜΥΛΩΝΑΣ ΙΩΑΝΝΗΣ & ΛΟΙΠΟΙ ΣΥΝΙΔ'
 'ΣΙΔΕΡΗΣ ΔΗΜΗΤΡΙΟΣ & ΣΙΑ ΑΕ' 'ΣΕΚΟΠΟΥΛΟΥ ΙΩΣΗΦΙΝΑ' 'ΤΣΑΚΙΡΗ ΧΡΙΣΤΙΝΑ'
 'ΒΑΣΙΛΟΠΟΥΛΟΣ ΙΩΑΝΝΗΣ' 'Ε. ΣΠΑΘΑΡΙΩΤΗ ΑΕ' 'ΜΠΑΡΑΜΠΟΥΤΗΣ ΚΩΝΣΤΑΝΤΙΝΟΣ'
 'ΣΤΕΦΑΝΟΥ ΓΕΩΡΓ' 'ΜΑΝΤΖΟΥΡΙΔΗΣ ΣΩΤΗΡΙΟΣ' 'ΜΑΝΤΖΑΡΗΣ ΔΗΜΗΤΡΙΟΣ'
 'ΤΣΑΜΠΑΡΛΙΔΗΣ ΓΕΩΡΓΙΟΣ ΚΛΠ' 'ΚΑΡΝΑΧΩΡΙΤΗ ΑΝΝΑ'
 'ΓΕΩΡΓΑΚΗΣ ΔΗΜΟΣΘ & ΛΟΙΠΟΙ ΣΥΝΙΔ' 'ΓΚΑΤΖΩΝΗΣ ΑΝΤΩΝΗΣ ΚΛΠ ΣΥΝΙΔ'
 'ΠΡΩΤΟΓΕΡΟΣ ΘΩΜΑΣ' 'ΙΩΣΗΦ ΓΟΥΜΕΝΑΚΗΣ & ΣΙΑ Ε.Ε.' 'ΤΡΟΥΠΑΚΗΣ ΘΕΟΦΑΝΗΣ'
 'ΤΣΟΥΜΑΣ ΠΕΤΡΟΣ ΚΛΠ ΣΥΝΙΔ' 'ΑΝΑΓΝΩΣΤΟΠΟΥΛΟΣ ΑΘΑΝ, ΝΙΚ ΚΛΠ'
 'ΣΚΑΦΙΔΑΚΗΣ ΝΙΚ & ΛΟΙΠΟΙ ΣΥΝΙΔ' 'ΒΟΡΡΕΑΣ ΠΑΝΤΕΛΗΣ'
 'ΡΟΥΣΣΟΥ ΑΝ & ΠΑΠΑΘΑΝΑΣΙΟΥ ΜΑΡΙΑ' 'ΑΠΟΣΤΟΛΟΥ ΝΕΣΤΩΡ ΚΛΠ ΣΥΝΙΔ'
 'ΕΛΥΡΟΣ Α.Ε.' 'ΒΕΝΕΤΣΑΝΟΣ ΠΕΤΡΟΣ' 'ΚΟΥΤΣΟΓΙΑΝΝΗΣ ΔΙΟΝΥΣΙΟΣ ΤΟΥ ΛΕΩΝ'
 'Γ  ΝΟΙΚΟΚΥΡΑΚΗ ΚΑΙ ΣΙΑ ΟΕ' 'ΚΑΛΥΨΩ ΑΕΒΕ                   00'
 'ΛΟΥΠΑΣΑΚΗΣ-ΛΟΥΠΑΣΗΣ ΠΑΝΑΓΙΩΤΗΣ' 'ΣΑΣΣΑΛΟΥ ΣΟΦΙΑ & ΛΟΙΠΟΙ ΣΥΝΙΔ'
 'ΣΑΣΣΑΛΟΥ ΣΟΦΙΑ' 'ΓΑΒΑΛΑΚΗ ΕΥΓΕΝΙΑ ΚΛΠ ΣΥΝΙΔΙΟΚΤ.'
 'ΒΟΥΛΓΟΥΡΙΔΗ ΠΑΡΑΣΚΕΥΗ' 'SOUTHROCK PROPERTY COMPANY ONE A.E.'
 'ΞΥΔΙΑΣ ΔΗΜΗΤΡΙΟΣ & ΛΟΙΠΟΙ ΣΥΝ' 'ΚΥΡΙΑΚΙΔΗΣ ΣΩΤΗΡΙΟΣ & ΛΟΙΠΟΙ ΣΥΝ'
 'ΛΟΓΟΘΕΤΗΣ ΝΙΚ ΗΡΑΚΛ ΜΕΣΣΗΝΗΣ Θ Α' 'ΛΟΓΟΘΕΤΗΣ ΗΡΑΚΛΗΣ & ΛΟΙΠΟΙ ΣΥΝΙΔ'
 'ΑΦΟΙ ΚΑΡΑΤΖΑ Α.Ε.' 'ΤΣΙΓΚΟΣ ΔΗΜΗΤΡΗΣ & ΙΣΙΔΩΡΟΣ' nan]
===

In [ ]:
db = pd.DataFrame()
for key, df in dfs.items():
    temp = df[cols_to_keep].copy()

## ΑΡΧΕΙΑ

In [122]:
df_pollaplos = pd.read_excel("../" + datapath + "ΣΥΓΚΡΙΤΙΚΟΣ ΕΥΔΑΠ 02.10.2025.xlsx", sheet_name="ΠΟΛΛΑΠΛΟΣ 08.09.2025")
df_single    = dfs['914632'].copy()

In [123]:
df_pollaplos.shape, df_single.shape

((684, 51), (480, 43))

In [120]:
df_single

,ΔΙΑΔΡΟΜΗ,ΑΡ.ΠΑΡΟΧΗΣ,ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΑΠΌ,ΠΕΡΙΟΔΟΣ ΚΑΤΑΝΑΛΩΣΗΣ ΕΩΣ,ΗΜΕΡ.ΛΗΞΕΩΣ,ΗΜ.ΚΑΤΑΝΑΛΩΣΗΣ,ΠΕΡΙΦ.ΓΡΑΦ.,ΤΙΜΟΛΟΓΙΟ,ΙΔΙΟΚΤΗΤΗΣ,ΕΝΟΙΚΟΣ,...,ΟΑΠ,ΦΠΑ ΤΙΜ.,ΦΠΑ ΛΟΙΠΩΝ,ΕΡΓΑΣΙΕΣ,ΔΙΑΦ.ΚΕΡΜ.,ΚΥΡΙΑ ΟΦ.,ΠΙΣΤΩΤΙΚΟ,ΟΦΕΙΛΗ,ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ,ΗΜΕΡΟΜ.ΕΚΔΟΣΗΣ
0,NaN,534,NaT,NaT,2025-08-26,NaN,Α,NaN,ΜΕΤΟΧ ΤΑΜΕΙΟ ΠΟΛΙΤΙΚΩΝ ΥΠΑΛΛΗΛΩΝ,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,0.16,0.0,0.16,0.0,0.16,20250007703139,2025-08-26
1,NaN,688358,NaT,NaT,2025-08-26,NaN,Α,NaN,ΜΕΤΟΧ ΤΑΜΕΙΟ ΠΟΛΙΤΙΚΩΝ ΥΠΑΛΛΗΛΩΝ,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,0.04,0.0,0.04,0.0,0.04,20250007703153,2025-08-26
2,NaN,569,NaT,NaT,2025-08-26,NaN,Α,NaN,ΤΡΑΠΕΖΑ EUROBANK A.E.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,5.83,0.0,5.83,0.0,5.83,20250007703140,2025-08-26
3,NaN,570,NaT,NaT,2025-08-26,NaN,Α,NaN,ΤΡΑΠΕΖΑ EUROBANK A.E.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,0.05,0.0,0.05,0.0,0.05,20250007703141,2025-08-26
4,NaN,571,NaT,NaT,2025-08-26,NaN,Α,NaN,ΤΡΑΠΕΖΑ EUROBANK A.E.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,0.11,0.0,0.11,0.0,0.11,20250007703142,2025-08-26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,NaN,1544539,NaT,NaT,2025-08-26,NaN,Π,NaN,ΤΡΑΠΕΖΑ EUROBANK A.E.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,0.03,0.0,0.03,0.0,0.03,20250007703164,2025-08-26
476,43.0,2105049,2025-05-15,2025-08-20,2025-10-02,98.0,Σ,Β1,ΤΡΑΠΕΖΑ EUROBANK A.E.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,1.71,0.30,1.19,NaN,0.0,8.75,0.0,8.75,20250007596590,2025-08-21
477,51.0,1851989,2025-05-24,2025-08-27,2025-09-29,96.0,Σ,Β1,ΑΦΟΙ ΚΑΡΑΤΖΑ Α.Ε.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,4.68,0.81,1.89,NaN,0.0,16.82,0.0,16.82,20250007893560,2025-09-01
478,27.0,2168598,2025-05-06,2025-07-26,2025-09-03,82.0,Σ,Β1,ΤΡΑΠΕΖΑ EUROBANK A.E.,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,26.80,0.66,NaN,0.0,236.40,0.0,236.40,20250007143624,2025-08-05
479,NaN,1823289,NaT,NaT,2025-08-26,NaN,Σ,NaN,ΤΣΙΓΚΟΣ ΔΗΜΗΤΡΗΣ & ΙΣΙΔΩΡΟΣ,ΤΡΑΠΕΖΑ EUROBANK A.E.,...,NaN,0.00,NaN,0.01,0.0,0.01,0.0,0.01,20250007703316,2025-08-26

In [113]:
print("Comparison between df_pollaplos and df_single:")
print(f"df_pollaplos shape: {df_pollaplos.shape}")
print(f"df_single shape: {df_single.shape}")
print("=" * 50)

# Compare columns
pollaplos_cols = set(df_pollaplos.columns)
single_cols = set(df_single.columns)

common_columns = pollaplos_cols.intersection(single_cols)
pollaplos_only = pollaplos_cols - single_cols
single_only = single_cols - pollaplos_cols

print(f"Common columns: {len(common_columns)}")
print(f"Columns only in df_pollaplos: {len(pollaplos_only)} - {list(pollaplos_only)}")
print(f"Columns only in df_single: {len(single_only)} - {list(single_only)}")
print("=" * 50)

# Check data types for common columns
if common_columns:
    print("Data type comparison for common columns:")
    for col in sorted(common_columns):
        pollaplos_dtype = df_pollaplos[col].dtype
        single_dtype = df_single[col].dtype
        if pollaplos_dtype != single_dtype:
            print(f"  {col}: df_pollaplos({pollaplos_dtype}) vs df_single({single_dtype})")

Comparison between df_pollaplos and df_single:
df_pollaplos shape: (684, 51)
df_single shape: (480, 43)
==================================================
Common columns: 43
Columns only in df_pollaplos: 8 - ['Unnamed: 44', 'Unnamed: 45', 'Unnamed: 47', 'Unnamed: 43', 'Unnamed: 46', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50']
Columns only in df_single: 0 - []
==================================================
Data type comparison for common columns:
  ΑΡ.ΠΑΡΑΣΤΑΤΙΚΟΥ: df_pollaplos(float64) vs df_single(int64)
  ΑΡ.ΠΑΡΟΧΗΣ: df_pollaplos(float64) vs df_single(int64)
  ΑΦΜ: df_pollaplos(float64) vs df_single(int64)
  ΠΑΡ.ΕΝΔΕΙΞΗ: df_pollaplos(float64) vs df_single(int64)
  ΠΡΟΗΓ.ΕΝΔ.: df_pollaplos(float64) vs df_single(int64)
  ΠΡΟΣΘ: df_pollaplos(float64) vs df_single(int64)
  ΤΡΙΜ: df_pollaplos(float64) vs df_single(int64)